---
title: "Eksempel 1"
format: html
editor: visual
---

## Førsteutkast

```{r, echo=TRUE}

# Laster bibliotek
library(tidyverse)
library(janitor)
library(readxl)

# Laster inn data
df <- read_excel("SkjemaCQ.xlsx", 
                 col_types = c("numeric", "numeric", "text", "date", "numeric",
                               "text", "numeric", "skip", "text", "text", "skip",
                               "text", "text", "skip", "text", "text", "skip",
                               "numeric", "skip", "numeric", "numeric", "text", 
                               "numeric", "skip", "text", "skip", "text", "skip", 
                               "text", "text", "numeric", "text", "text"))
```

```{r, echo=TRUE}
# Antall unike pasienter - 540?
(pasienter <- df |> distinct(Navn, Fødselsdato))
```

```{r, echo=TRUE}
# Andel duplikater per navn - 24? Må sjekkes nærmere
pasienter %>% group_by(Navn) %>% summarise(n=n()) %>% filter(n>1) |> print(n = 30)
```

```{r, echo=TRUE}
# Navn skrevet feil, men samme pasient, eller flere med lik fødselsdag? Må sjekkes nærmere
pasienter %>% group_by(Fødselsdato) %>% summarise(n=n()) %>% filter(n>1) |> print(n = 80)
```

```{r, echo=TRUE}
# Diagnoser - noen justeringer og korreksjoner må til
df |> tabyl(Diagnose) |> adorn_pct_formatting(digits = 1) |> adorn_totals()

```

```{r, echo=TRUE}
# Ledd/ben - mulig med færre kategorier? Lettere for senere anelyser.
df |> tabyl(`Ledd/ben`, show_na = FALSE) |> adorn_pct_formatting(digits = 1) |> adorn_totals()
```

```{r, echo=TRUE}
# Type ortopediske inngrep - 84 (!) variasjoner
# Redusere og senere sammenslå for sammenligne
df |> tabyl(`Type ortopedisk-inngrep`, show_na = FALSE) |> adorn_pct_formatting(digits = 1)
```

```{r, echo=TRUE}
# Type ikke-ortopediske inngrep - 211 (!) variasjoner
# Redusere og senere sammenslå for å sammenligne
# For å svare på kategorier hjerte-kar, cancer, GI-inngrep, 
# mindre inngrep osv, så må inngrepene "spesifiseres bedre
df |> tabyl(`Type ikke ortopedisk-inngrep`, show_na = FALSE) |>  adorn_pct_formatting(digits = 1)
```

```{r, echo=TRUE}
# Alder ved første ortopediske kirurgi - eksempel 1997
df |> 
  group_by(Navn) |> 
  filter(`År gjennomgått kir.` == 1997, `Ikke ortopedisk` == 0) |> 
  distinct(Navn, Alder) |> 
  pull(Alder) |> 
  mean()
```

```{r, echo=TRUE}
# Alder ved første ikke-ortopediske kirurgi - eksempel 1997
df |> 
  group_by(Navn) |> 
  filter(`År gjennomgått kir.` == 1997, `Ikke ortopedisk` == 1) |> 
  distinct(Navn, Alder) |> 
  pull(Alder) |> 
  mean()
```

```{r, echo=TRUE}
# Alder ved første ortopediske kirurgi - eksempel 2023
df |> 
  group_by(Navn) |> 
  filter(`År gjennomgått kir.` == 2023, `Ikke ortopedisk` == 0) |> 
  distinct(Navn, Alder) |> 
  pull(Alder) |> 
  mean()
```

```{r, echo=TRUE}
# Alder ved første ikke-ortopediske kirurgi - eksempel 2023
df |> 
  group_by(Navn) |> 
  filter(`År gjennomgått kir.` == 2023, `Ikke ortopedisk` == 1) |> 
  distinct(Navn, Alder) |> 
  pull(Alder) |> 
  mean()
```
