# Diagnosis

## Incidence and co-morbidity

As mentioned above, AH is rare and the incidence is about 1.5/million per year. It is primarily a disease affecting the elderly (median age 64–78 years), but can also be associated with pregnancy. Most cases are idiopathic (43.6%-51.9%) but AHA is also associated with malignancy (6.4%-18.4%), autoimmune disorders (9.4%-17.0%), infections and dermatologic conditions [@Collins-07-BLOOD; @Knoebl-12-JTH; @Delgado-03-BJH; @Borg-13-HAE; @Huang-15-JFMA; @Tiede-15-BLOOD]. Rarely, AH arises as idiosyncratic reactions to medication including antibiotics, psychiatric and immunomodulatory drugs [@Franchini-07-MSM]. The relative high number of co-existing autoimmune disorders in the patients or among his/her relatives may be striking. Therefore, findings suggesting polymorphisms in immune regulatory genes to be associated with the incidence of acquired haemophilia may be of importance [@Pavlova-08-HAE; @Oldenburg-08-PHARM]. It has also been hypothesized that encounter of antigenically different, allogeneic FVIII after blood transfusion may challenge inhibitor formation after presentation on MHC class II and support for this assumption was found in a study by Tiede et al [@Tiede-10-AH].

## Symptoms and signs and clinical course

Easy bruising with extensive enlargement, muscle haematomas and profuse bleeds after trauma and surgery are the most common symptoms in a patient who has never had any signs of bleeding tendency earlier. Muscle bleeds and gastrointestinal (GI) bleeds are also common, but in contrary to congenital haemophilia, joint bleeds are rare [@Collins-07-BLOOD; @Knoebl-12-JTH; @Delgado-03-BJH]. Haematuria with intermittent clotting and occlusion of ureter(s) may decrease renal function. Massive bleeds may occur after intravenous venipuncture if special care is not taken. Severe bleeds may be life-threatening. Because of the second-order kinetics of the anti-FVIII antibodies, FVIII levels are not predictive of bleeding risk and patients can have clinically significant bleeding despite only modestly reduced FVIII activity levels. 
Mortality in AHA is estimated to be 20% among patients >65 years and those with underlying malignancies. Although the primary cause of death is the underlying disease (46%) [@Knoebl-12-JTH], the cause of death is unknown in many (38%) [@Hay-06-BJH], reflecting limited follow-up in most studies. Immunosuppressive therapy (IST) to eliminate the antibodies and decrease bleeding risk is recommended but is associated with high mortality, accounting for 16% of all deaths (4.2% of patients) in EACH2 [@Knoebl-12-JTH]. Other fatal and nonfatal complications include thrombotic events such as myocardial infarction and stroke [@Borg-13-HAE; @Tiede-15-BLOOD].

## Laboratory screening methods

APTT is usually prolonged, while Prothrombin time, PT (INR) is normal. Platelet and leukocyte counts are generally normal. The erythrocyte count and the haemoglobin value may be low due to bleeds.

## Specialized laboratory methods

The diagnosis should be confirmed at a specialized coagulation laboratory.

### Blood sampling and transport

Blood samples are drawn in vacutainer tubes containing 3.2% (0.109 M) trisodium citrate by direct venipuncture.

*	Fill tube correctly to the mark (line) and mix thoroughly with anticoagulant (reverse gently the tube(s) immediately 5-10 times).

*	Centrifuge within 1 hour of phlebotomy to obtain platelet poor plasma (<10x10^9^/L) at 2000 g for 20 minutes.

* If testing cannot be performed within four hours from phlebotomy, the plasma should be transferred by pipetting to another tube and frozen at -70°C for later analysis.

* Frozen plasma must be transported on dry ice. 

### Testing at the coagulation laboratory

Mixing test (can also be performed at non-specialized laboratories): Patient plasma is mixed with an equal volume of normal   plasma (NPP; 1+1) and APTT analyzed immediately and/or incubated for 1-2 h at 37°C. In normal conditions, the APTT will lengthen slightly if incubated 1-2 h at 37°C, because of a spontaneous decay of the labile FVIII. A prolonged APTT in a factor deficient plasma will be corrected when the plasma is mixed 1:1 with normal plasma, whereas presence of an inhibitory antibody against a coagulation factor or lupus anticoagulant, does not give a correction after mixing (anticoagulant in the plasma must be excluded). In acquired haemophilia, weak affinity inhibitors can sometimes only be detected if a longer incubation time (1-2h) is used prior to analysis (see below autoantibodies).

## Specific methods

The functional activity of FVIII or, occasionally, other coagulation factors such as FIX, can be measured with either clot-based or chromogenic assays. Autoantibodies to other factors are extremely rare. The recommended procedure for diagnosing inhibitory antibodies to coagulation factors is the Bethesda-Nijmegen method [@Verbruggen-95-TH]. The antibody titer is expressed in Bethesda units (BU). One Bethesda Unit is defined as the quantity of antibody, which reduces the FVIII activity by half in normal plasma. A test sample is prepared by mixing equal volumes of patient plasma with NPP and then measure the residual factor activity in the plasma mixture after 2h incubation. A control sample is prepared in parallel with NPP mixed with an equal volume of FVIII-deficient plasma. Both test and control samples are incubated for 2 h at 37°C and then the factor activities in both samples are measured.  The factor activity is measured using a clot-based or chromogenic method. The Bethesda assay is most suitable for patients that do not have measurable factor activity. If the patient has an activity > 0.10 kIU/L (10%), we recommend heat-inactivation of the plasma sample endogenous activity at 56˚C for 1h before analysis.

## Characteristics of the autoantibodies

Autoantibodies against FVIII are composed predominantly of IgG, most often of the IgG4 subclass, and have a preponderance of kappa light chains. The main antigenic epitopes of the FVIII molecule are the A2 and C2 domains. Bound inhibitors block the binding of FVIII to phospholipids, von Willebrand factor and cofactors of the FVIII molecule. The autoantibodies follow a type II inactivation pattern, which means that there is incomplete neutralization of FVIII activity. Therefore, variable levels of residual FVIII activity may be detectable in patient plasma despite the concomitant presence of high titers of the FVIII inhibitor. The complex type II kinetics makes it difficult to clinically evaluate the inhibitor titer and factor levels. This is in contrast to alloantibodies seen in patients with congenital haemophilia which follow type I kinetics characterized by complete inactivation in a linear relationship between antibody titer and residual FVIII activity.

## Recommendations

*	Acquired haemophilia should be suspected in patients with prolonged APTT, but normal INR and signs of bleeding.

*	If coagulations factor analyses is not readily available, a mixing test could be performed to strengthen the suspicion. The presence of an inhibitory antibody against a coagulation factor does not give a correction of APTT after mixing with normal plasma.

*	The diagnosis should be confirmed at a specialized coagulation laboratory.

*	The recommended procedure for diagnosing inhibitory antibodies to coagulation factors is the Bethesda-Nijmegen method.

*	Type II kinetics of the antibodies results in poor correlation between antibody titer and FVIII levels and caution is warranted when interpreting the results.
