# Summary

Acquired haemophilia (AH) is a severe bleeding disorder caused by inhibiting autoantibodies against a coagulation factor, most often factor (F) VIII (acquired haemophilia A, AHA), developing in a patient with no previous history of bleeding. Due to the rarity of acquired haemophilia B, with antibodies formed against FIX, all data available and presented in this guideline primarily concerns acquired haemophilia A. 

It is a rare disorder with an incidence of about 1-2/one million per year. Mostly elderly persons are affected with the exception of the rare occurrence in females postpartum. The APTT is usually prolonged but other laboratory screening tests for haemostasis like platelet count and prothrombin time are normal. Patients with AH represent a demanding clinical challenge. The mortality rate is high (3.3%-22% in different studies)[@Collins-07-BLOOD; @Knoebl-12-JTH] and treatment involves the use of specific and expensive coagulation promoting products. The diagnosis requires identification of autoantibodies (inhibitors) with a specialized test. Consequently, both special laboratory facilities and clinical experience are required to deal with this group of patients. **The physician on duty at a haemophilia centre should be consulted.**

In recent years, valuable information was gathered regarding e.g. incidence, frequency of co-existing disorders, mortality and risk of bleeding as well as eradication therapy. These studies include: 1) a meta-analysis of 234 evaluated patients from the literature presented by Delgado et al. [@Delgado-03-BJH], 2) a surveillance study in the United Kingdom conducted by Dr Peter Collins [@Collins-07-BLOOD], including altogether 172 patients diagnosed in England and Wales with acquired haemophilia A (AHA) during a two-year-period starting in 2001, and  3) the  pan-European register, EACH/EACH2 [@Knoebl-12-JTH], including 501 (266 male, 235 female) patients from 117 centres and 13 European countries. More recent studies include the prospective Surveillance des Auto antiCorps aucours de l’Haemophilie Acquise—SACHA [@Borg-13-HAE] surveillance study including 82 patients, a retrospective Taiwanese study including 65 patients [@Huang-15-JFMA] as well as the prospective German, Austrian and Swiss Society on Thrombosis and Haemostasis including 102 patients [@Tiede-15-BLOOD].