# Adolescence

#### Revision by: Susanna Ranta (Stockholm), Pia Petrini (Stockholm), Nadine Gretenkort (Malmö), Kaisa Vepsäläinen (Kuopio), Heidi Glosli (Oslo) and Marianne Hoffman (Copenhagen) {-}

### Recommendation {-}

*	A transition program is recommended to secure continuous adherence in adolescents during transfer from pediatric to adult service.

Adolescence is the time of rapid physical, social and cognitive development which occurs during the transition from childhood to adulthood, usually between the ages of 10 and 24 years. This is a challenging time for any teenager and even more so for those with a chronic disease. For them it is often harder to break family ties, harder to feel accepted by their peer group and to be realistic about their future. Young teenagers need to move towards independence and for people with hemophilia this includes achieving self-management, maintaining adherence to therapy and coping with the impact of hemophilia on lifestyle [@Petrini-09-HAE].

The developmental tasks of adolescence include emotional separation from parents and establishment of autonomy. Peers have a central role in building up the personality.  Adolescents seek new experiences and higher levels of rewarding stimulation, and often engage in risky behavior without considering future outcomes or consequences. Poor compliance with hemophilia therapy during adolescence in combination with risky behaviors, may result in serious and recurrent bleeding episodes with impact on future outcomes. The teenager may for the first time question their medical regimen and be ashamed of the diagnosis [@Young-12-HAE].

In a global survey of treatment strategies in hemophilia A involving 147 hemophilia treatment centers, compliance was rated according to age. Compliance with all types of prophylactic therapy was the highest in children up to 12 years of age, with more than half achieving high ($\geq$ 90%) adherence. The number achieving this adherence level dropped to 13%, however, in adolescents aged 13-18 years [@Geraghty-06-HAE].

A Scandinavian survey in young men with severe and moderate hemophilia showed that the average age for a patient to take over responsibility for their treatment was 14 years, but 25% required parental assistance in hemophilia-related care until a mean age of 17.2 years. A majority (68%) treated bleeds immediately and 60% used extra infusions when needed. Thus one-third of them put themselves at risk for complications by an unwillingness to recognize the need for treatment. Over 40% had at some time failed to follow the treatment regimen [@Lindvall-06-HAE].

Caregivers can support adherence by education, encouragement, and by providing positive feedback to the patient.

The perception that treatment is a normal part of life is shown to increase adherence to therapy in adolescents and treatment individualized to patients’ bleeding pattern and lifestyle can improve compliance.

The challenges faced by the adolescent should be addressed in the years before transition to the adult clinic. Arranging efficient end caring transfer for young people with hemophilia is one of the great challenges in the coming century.

Transition programs are necessary even when pediatric and adult services are in the same hospital, as geographical closeness often does not translate into a close professional relationship. A joint pediatric-adult clinic is very useful to introduce adolescents to adult physicians and to hand over clinical issues. Joint clinics between pediatric and adult health-care teams can improve the transfer and help young people to communicate with the new team.
