# Carriers of haemophilia

#### Revision by: Anna Olsson (Gothenburg) {-}

## Background

Due to X-chromosome inactivation the clotting factor levels in carriers are expected to be about 50% of the levels of non-carriers. However, the factor levels may vary from very low to the upper limit of normal values [@Plug-06-BLOOD]. Carriers with factor levels less than 0.40 kIU/L are diagnosed with haemophilia. In addition, carriers may have bleeding symptoms similar to mild haemophilia even with factor levels close to normal range. It is estimated that approximately 20% of carriers are symptomatic to some degree and may require haemostatic support during surgery, trauma and delivery [@Plug-06-BLOOD]. The factor level of an obligate or possible carrier should be checked at a young age and especially prior to an invasive procedure or in case of bleeding symptoms. The timing of genetic testing for carriership needs careful consideration taking into account age and psychosocial issues [@Dunn-08-HAE]. It’s also important that the girl as well as her family understand that a normal factor level does not exclude carriership.

## Prenatal diagnosis

Before planning a family the carrier and her partner should be offered contact with a genetic counsellor and an educational visit at the HTC. Counselling should include discussion of the genetic risk and the options of prenatal testing that are available [@Myrin-Westesson-13-HAE].

Chorionic villus sampling (CVS) is the principal method used for prenatal diagnosis of haemophilia. The procedure is performed during the 11 to 13th week of gestation. If later in pregnancy, an amniotic fluid sample may be used as DNA source for prenatal diagnosis. Both procedures are associated with a risk of miscarriage at approximately 1% [@Mujezinovic-07-OG]. Haemostatic cover should be arranged prior to any invasive procedure if the factor level is <0.50 kIU/L.  Knowledge of foetal gender allows appropriate management of labour and delivery. Ultrasound diagnosis can be used from late second trimester and is based on visualization of the external genitalia [@Elejalde-85-JUM]. Analysis of free foetal DNA (ffDNA) in the maternal circulation is an alternative non-invasive means of determining foetal sex [@Devaney-11-JAMA]. Pre-implantation genetic diagnosis (PGD) may be an option for couples who would not consider termination of a pregnancy and for those with concurrent infertility. Since in-vitro fertilization is used, the technique is labour intensive and technically challenging [@Lavery-09-BJH]. 

## Management of gynaecological and obstetrical bleedings

One of the first haemostatic challenges a carrier may be facing is menstrual bleeding. Girls with haemophilia should have a treatment plan prior to menarche for the possibility of excessive menstrual blood loss. Excessive bleedings may appear with the first or any following menstrual period during the adolescence. Haemostatic therapeutic options for the management of menorrhagia include tranexamic acid, DDAVP and clotting factor replacements. Hormonal therapy should be considered and, if appropriate, introduced by a gynaecologist with knowledge of bleeding disorders in collaboration with HTC [@Lee-06-HAE].

During pregnancy the FVIII levels in carriers of haemophilia A may increase sufficiently to permit safe haemostasis during delivery. In carriers of haemophilia B the FIX level cannot be expected to increase to the same extent [@Chi-08-HAE]. Factor level should be checked at gestation week 32-34 to allow appropriate management of delivery and to assess the need for prophylactic treatment. A written delivery plan should be drawn up in advance and the delivery should take place in a unit with suitable expertise. As a general rule, prophylactic treatment to prevent from bleeding during delivery and postpartum is given to carriers with subnormal factor levels. If treatment is required, factor levels of 1.0 kIU/L should be aimed for to cover labour, delivery and the immediate postpartum period. The treatment should be continued to maintain factor levels above 0.50 kIU/L for at least three to four days after vaginal delivery and five to seven days after caesarean section [@Lee-06-HAE]. Tranexamic acid may be used in combination with replacement therapy and as a sole therapy for carriers with factor levels within normal range when clinically required. The risk for secondary postpartum haemorrhage is increased when clotting factors return to pre-pregnancy levels after delivery and tranexamic acid should be continued postpartum as needed [@Sentilhes-15-BJA]. DDAVP may be used in carriers of haemophilia A to improve haemostasis after the child is born. Factor levels > 0.50 kIU/L are required for insertion and removal of an epidural catheter and for spinal anaesthesia [@Chi-09-TH; @Choi-09-AA]. Vaginal delivery is recommended if no other obstetric concerns, however caesarean section should be considered early when needed to avoid emergency caesarean. Assisted vaginal delivery, vacuum extraction and use of forceps, as well as foetal blood sampling and foetal scalp electrode should be avoided for male babies at risk of haemophilia [@Davies-16-HAE; @Ljung-10-HAE; @James-10-HAE]. Cord blood sampling and diagnostic testing is recommended for all male babies. Vitamin K should be administered by an oral regimen to neonates with low factor levels [@Chalmers-11-BJH].
