# Comorbidities in the ageing patients with hemophilia

#### Revision by: Elina Lehtinen (Helsinki) {-}

### Summary of recommendations {-}

*	The challenges with comorbidities developing during aging are best managed in close multidisciplinary collaboration with different medical and surgical specialists and networking with patient’s local hematologist and primary care physician.

*	Joint disease: The goal is to try to protect and improve joint function, relieve pain and assist the patient in resuming normal activities of daily living by secondary factor prophylaxis, physiotherapy, lifestyle changes, pain management, and orthopedic procedures.

*	Osteoporosis: Assessment of bone mineral density status by imaging studies (DEXA scan) and laboratory evaluation are recommended as part of comprehensive hemophilia care. Osteopenia can be prevented or reduced by supplement of calcium, vitamin D and exercise, while osteoporosis necessitates specialist treatment with bisphosphonates, estrogens, calcitonins or monoclonal antibodies.

*	Infection related issues: HAART treatment may increase the risk of metabolic syndrome, diabetes, renal insufficiency and atherosclerotic cardiovascular disease and frequency and severity of hemarthrosis, thus close laboratory monitoring and follow-up is recommended.

*	Metabolic syndrome: Effective prevention strategies are necessary throughout life. Lipid profile should be measured in ageing hemophilia patients at risk of cardiovascular disease and treatment initiated according to the general guidelines. Glucose levels should be checked annually, especially if overweight. Treatment management, regular clinical and laboratory follow-up should be coordinated with the primary care physician, with consultation services from internal medicine and endocrinology.

*	Cardiovascular disease: PWH with cardiovascular disease should receive routine care adapted to the individual situation, in discussion with a cardiologist. DDAVP (desmopressin) should be avoided and thrombolysis is not recommended. Bare-metal stent should be favored over drug-eluting stent or alternatively coronary artery bypass grafting. Radial artery access site is preferred to reduce bleeding risk. For valve replacement, material that does not necessitate anticoagulation should be chosen. Anticoagulation and antiplatelet therapies are possible with replacement therapy. For atrial fibrillation, no anticoagulation, low-dose aspirin or warfarin are considered depending on basal factor levels and stroke risk.

*	Renal disease: Etiology for recurrent hematuria should be evaluated especially in older patients. Peritoneal dialysis could be the preferred choice since no anticoagulation is needed. Hemodialysis is performed with tailored prophylactic factor dosing.

*	Cancer: New, aggravated or recurring bleeding episodes should be promptly investigated and relevant hemostatic treatment must be given to prevent bleeds in the setting of diagnostic interventions and prior to surgical, chemo-, or radiotherapeutic treatment. For prostate cancer diagnostics and treatment, antifibrinolytics should be used with caution.

## Introduction

Improved treatment has extended life expectancy for PWHs during the last three to four decades making them susceptible not only to complications of hemophilia, but also to age related co-morbidities same as in the general male population [@Franchini-10-BJH; @Khleif-11-JAR; @Marchesini-18-HAE; @Miesbach-17-HAE; @Harrison-17-HAE]. Apart from the initial devastating effects on morbidity and mortality associated with the transmission of viral pathogens during the 1980’s and early 1990’s, the availability of factor concentrates and improved treatment regimens have had a favorable influence on longevity and quality of life of PWHs.

At present with only scarce evidence based data available, little is known about how to manage these "new" concomitant illnesses in a scientific manner, apart from hemophilic arthropathy and chronic infections with HIV (human immunodeficiency virus) and HCV (hepatitis C virus). Comorbidities like metabolic syndrome, cardiovascular and renal disease, along with infection related issues and cancer represent a series of challenges to physicians treating PWHs. Comorbidities should be managed appropriately as they may emphasize problems associated with hemophilia and impact the patient's quality of life. Thus, expertise from specialists in e.g. cardiology, neurology, oncology, nephrology and urology, as well as collaboration with patients' primary care physician need to be included in the multidisciplinary team of physicians treating elderly PWHs in comprehensive hemophilia care centers [@Hollingdrake-16-HAE; @Boccalandro-18-HAE].

## Current status and recommendations / managing suggestions

### Joint disease

The most prominent co-morbidity in middle-aged and older PWHs is irreversible joint arthropathy [@Franchini-10-BJH; @Khleif-11-JAR; @Stephensen-13-HAE]. Due to lack of treatment, recurrent hemarthroses result in initial synovial hypertrophy and neoangiogenesis further increasing the risk of bleeding and later on result in degenerative changes of the joint. This leads to limited use of the affected, often weight-bearing joint, causes pain, muscle atrophy, anchylosis (reduces range of motion), contractures and osteoporosis, the latter express by a reduced bone mineral density (BMD) or impaired bone structure.The goal of treatment is to try to improve joint function, relieve pain and assist the patient in resuming to normal activities of daily living. Physiotherapy is an important treatment modality to improve or maintain muscle function and joint motion, may reduce the risk of falls and encourage an interest for an active lifestyle. Appropriate pain management including suitable medication needs to be carried out to prevent further deterioration, but also needs to be monitored closely for side effects [@Mannucci-09-BLOOD]. Lifestyle changes, e.g. weight loss and regular exercise, would also be beneficial. The use of secondary prophylaxis (regular treatment with factor concentrate after onset of arthropathy) reduces bleeding frequency and facilitates rehabilitation, but does not alter established degenerative changes that worsen with age. Despite adequate treatment and even in the absence of an inhibitor, target joint bleeds require procedures, such as radiosynovectomy to control synovial hypertrophy or at times angiographic embolization to stop joint bleeding from arterial origin [@Mannucci-09-BLOOD; @Konkle-12-AJH]. To reduce severe pain and disability arthroscopy, arthrodesis, arthroplasty or total joint replacement are efficient interventions.  Consultations services and multidisciplinary programs with rehabilitation medicine, orthopedics and pain clinics are integral part of the hemophilia care team [@Boccalandro-18-HAE].

### Osteoporosis

Osteoporosis is an under-recognized problem in males. There are many paredisposing factors for patients with haemophilia, such as prolonged periods of immobility, reduced weight bearing and co‐morbidities associated with bone loss [@Gerstner-09-HAE]. Osteopenia can be prevented or reduced through a supplement of calcium, vitamin D and weight bearing exercise, while osteoporosis necessitates specialist treatment with one or several drugs including bisphosphonates, estrogens, calcitonins and monoclonal antibodies [@Konkle-09-HAE]. Thus, assessment of bone mineral density (BMD) by imaging studies (DEXA scan) and laboratory evaluation are recommended as part of comprehensive hemophilia care. Laboratory measurements include serum calcium, vitamin D levels, as well as markers of bone turnover, such as collagen I aminoterminal telopeptide (INTP or Ntx) from urine and procollagen I aminoterminal propeptide (PINP) from serum at baseline and as follow up of drug therapy. Testosterone levels and thyroid function studies are used for ruling out secondary causes for low bone density. Endocrinologist consultation should be utilized as needed.

### Infection related issues / complications

With the introduction of HAART (highly active antiretroviral treatment) a substantial decrease in HIV infection related deaths (over time) were seen [@Konkle-09-HAE]. Also the HIV related occurrence of NHL (non-Hodgkin lymphoma) has declined. HAART treatment increases the risk of metabolic syndrome, diabetes, renal insufficiency and atherosclerotic CVD (cardiovascular disease) in non-bleeding patients. A similar impact is suspected to apply to PWHs [@Franchini-10-BJH; @Mannucci-09-BLOOD]. Close laboratory monitoring is therefore recommended. HAART has also been reported to increase frequency and severity of hemarthrosis in hemophilia [@Konkle-09-HAE].

HCV is the major cause of chronic liver disease since genotype 1 responds poorly to treatment with subcutaneous Peg-IFN (pegylated interferon) and oral ribavirin. Poor treatment response has also been seen in the numerous PWHs who have a HIV and HCV co-infection. Those who are co-infected also have a marked increased risk for progression in their liver disease with a later risk of transformation from liver cirrhosis into HCC (hepatocellular carcinoma [@Franchini-10-BJH; @Khleif-11-JAR; @Mannucci-09-BLOOD]. Cirrhosis and portal hypertension with development of esophageal varices in combination with hypocoagulable state, including thrombocytopenia, increase the risk of bleeding [@Mannucci-09-BLOOD]. The only curative option is liver transplantation. Modern antiviral therapy including HCV protease inhibitors has markedly improved virological response rates. For patients not suitable for antiviral eradication therapy, disease progression should be followed according to current hepatology recommendations by utilizing laboratory (ALT, AFP) and modern imaging studies (fibroscan) as indicated [@Konkle-09-HAE]. Liver biopsies are rarely required. 
Infectious disease issues should be handled by hepatologist and infectious disease specialist as part of comprehensive hemophilia care. Treatment decisions should follow the national guidelines when available. 

### Metabolic syndrome

The term describes a complex of signs that increase the risk for type 2 diabetes, stroke and coronary artery disease. Effective prevention strategies throughout life are most important, as management of thrombotic complications in PWH is a special challenge. Diagnostic criteria include increased body mass index (BMI) >30 kg/m2, hypertension, dyslipidemia and hyperinsulinemia. Middle-aged PWHs tend to become obese and inactive due to severe arthropathy. In the other hand high BMI has been associated with a significant limitation in range of motion, increased arthropathic pain and increased risk of developing target joints. Mean cholesterol levels in patients with hemophilia have been reported to be lower than in the general population [@Rosendaal-90-BJH]. Lipid profile should be measured in ageing hemophilia patients at risk of cardiovascular disease and treatment initiated according to the general guidelines. Glucose levels should be checked annually, especially in those patients who are overweight. HAART treatment for HIV can result in hypertension, ischemic heart disease and dyslipidemia. Patients need appropriate treatment management, regular clinical and laboratory follow-up, which should also be coordinated with the primary care physician, with consultation services from internal medicine and endocrinology as needed [@Coppola-13-STH].

### Cardiovascular disease

Conflicting data exist on whether hemophilia protects against development of atherosclerosis and cardiovascular events [@Konkle-12-AJH; @Konkle-09-HAE; @Dolan-10-HAE; @Coppola-10-STH]. The same risk factors that affect the general population also seem to have impact on ageing PWHs. Increasing age, obesity, smoking, arterial hypertension, diabetes and dyslipidemia and inflammation (detected with high sensitivity-CRP and elevated factor VIII levels in hemophilia B) contribute to cardiovascular disease.

An institutional non-evidence-based Dutch guideline covers acute coronary syndrome (ACS) and percutaneous coronary intervention (PCI), where, after substitution with the deficient factor, the PWH is treated as close to general guidelines for non-PWHs as possible [@Schutgens-09-HAE]. The WFH guidelines (<a href>www.wfh.org</a>) similarly state that PWH with cardiovascular disease should receive routine care adapted to the individual situation, in discussion with a cardiologist. DDAVP (desmopressin) should be avoided as a hemostatic due to non-specific thrombogenic effects. Thrombolysis is not recommended. If necessary, documented in case series, a bare-metal stent should be favored since only four weeks of dual antiplatelet therapy is needed, or alternatively a coronary artery bypass grafting (CABG) [@Franchini-10-BJH; @Coppola-10-STH]. Radial artery access site is preferred over femoral, in order to minimize retroperitoneal or groin bleeds. Heparin can be administered according to standard cardiologic treatment protocols. Glycoprotein IIb/IIIa inhibitors used in PCI with stenting can be administered.

When treating valvular heart disease a material should be chosen that does not necessitate anticoagulation. Anticoagulation and antiplatelet therapies are possible taking in consideration of the baseline factor level and goals of replacement therapy [@Martin-16-BLOOD].

Emphasis should be made on not to "overtreat" in the course of replacement therapy especially with bypassing agents to avoid thrombotic events. A way to avoid hazardous peak levels during substitution therapy can be achieved by administering the needed coagulation factor by continuous infusion instead of bolus injections. Conversely, a certain empirical minimum factor level has to be maintained to allow for necessary antithrombotic treatment. In severe PWHs; >5% for aspirin alone and >30% for dual antiplatelet therapy [@Mannucci-09-BLOOD]. Prolonged use of aspirin is not recommended in severe hemophilia, although its use in patients on regular intensive prophylaxis is possible.

Virtually no data are available for defining treatment strategies for cerebrovascular and peripheral artery disease [@Coppola-10-STH]. Some recommendations are available based on case series regarding non-valvular atrial fibrillation and venous thromboembolism [@Martin-16-BLOOD]. The use of low molecular weight heparin or warfarin could be considered for short term treatment. For atrial fibrillation, no anticoagulation, low-dose aspirin or varfarin are considered depending on basal factor levels and stroke risk.

Erectile dysfunction can be seen as the first manifestation of vascular disease and endothelial dysfunction. It can accompany the metabolic syndrome or be caused by age-related changes in hormonal, neurological and psychological function [@Bar-11-HAE].

### Renal disease

In young PWHs, hematuria often is a benign, transient, usually idiopathic event. In older patients this bleeding symptom can be caused by several different conditions and etiology should be evaluated [@Holme-15-ASH]. In chronic renal disease uremia and anemia via platelet dysfunction increase the risk for kidney bleeding [@Holme-15-ASH; @Holme-16-HAE]. So does hypertension that can be caused by chronic renal disease and at the same time represents a risk factor for development of cardiovascular disease as well as cerebral hemorrhage. HIV-associated nephropathy and immune complex glomerulonephritis, nephrotoxicity of HAART and co-infection with HCV make up a large proportion of causes for renal insufficiency. If dialysis is needed, peritoneal dialysis could be the preferred choice since no anticoagulation is needed. This however could contain the risk for infection and peritoneal hemorrhage especially in patients co-infected with HIV and/or HCV [@Konkle-12-AJH; @Dolan-10-HAE; @Franchini-09-CTR]. For hemodialysis patients prophylactic factor dosing needs to be carefully tailored for access surgery and to allow the required anticoagulation. 

### Cancer

If malignancies that are a consequence of viral infection are excluded only a few clinical studies have addressed the issue of cancer in the ageing hemophilia population. It is uncertain whether the incidence of cancer in PWHs differs from that observed in the general middle-aged population [@Mannucci-09-BLOOD; @Franchini-09-CTR]. Persons with severe hemophilia tend to have a higher rate of virus-related cancers whereas milder forms present an overweight of non virus-related cancer types. At times patients are diagnosed with acquired hemophilia due to unusual bleeding of a cancer. Attention must also be drawn to the importance of prompt evaluation if a middle-aged PWH experiences new, aggravated or recurring bleeding episodes due to a second peak of inhibitor incidence at the age of 60 and above. Despite the increased risk of bleeding investigation and procedures should not be delayed or avoided in PWHs [@Astermark-12-HAE]. Relevant hemostatic treatment must be given to prevent bleeds both in the setting of diagnostic interventions and later on as well prior to surgical, chemo-, or radiotherapeutic treatment. One specific cancer type needs mentioning since it is one of the most frequent cancers in men, with increasing frequency up to the age of 70: prostate cancer [@Fogarty-12-HAE]. Prostate specific antigen (PSA) screening has reduced the percentage of disseminated disease at diagnosis more then 20-fold. Needle biopsy should be avoided if possible. Despite hemostatic treatment bleeding occurs, but is often mild to moderate and self-limiting. Antifibrinolytics should be used with caution and close observation for thrombus formation in the bladder and in the upper urinary tract with the risk of developing hydronephrosis. Several treatment options are available and seem to have equivalent survival rates. 

### Conclusion

Ageing PWHs present new challenges to hemophilia caretakers. Current management, in the absence of studies, is based on international consensus guidelines for the assessment, monitoring and follow-up of PWH. These include the WFH  (<a href>www.wfh.org</a>), the UKHCDO (<a href>www.ukhcdo.org</a>) and the EHTSB (European Haemophilia Therapy Standardization Board) [@deMoerloose-12-HAE]. On-going and future studies will hopefully clarify the most appropriate preventive measures and treatment regimens for co-morbidities, which often create management challenges in view of the hemostatic status of the PWH.

Centralized comprehensive hemophilia care is important throughout the life of PWHs. The challenges with comorbidities developing during aging are best managed in close multidisciplinary collaboration with different medical and surgical specialists and networking with patient’s local hematologist and primary care physician.
