
# History of hemophilia in the Nordic countries

#### Revision by: Eva Funding (Copenhagen), Fariba Baghaei (Gothenburg), Elina Lehtinen (Helsinki) {-}

\hfill\break

Prior to the availability of effective therapy, patients with severe hemophilia had a mean life expectancy of only about 16 years. However, since the late 1950’s the life expectancy of a newborn severe patient with hemophilia (PWH) receiving some form of replacement therapy has increased steadily [@Ikkala-60-LS]. In 1960 the average life expectancy had risen to 23 years in Sweden and it is now approaching normal in the Nordic countries, all of which now practice early and continuing prophylactic factor replacement therapy.

A plasma protein fraction correcting coagulation in hemophilia blood was first described in 1937 but only later termed coagulation factor VIII [@Patek-37-JCI]. In the 1950s, Margareta and Birger Blombäck at the Karolinska Institute in Stockholm while working on a method to purify fibrinogen by treating Cohn’s Fraction I with a glycine solution found that fibrinogen and Factor VIII (and also as it later turned out, von Willebrand factor) remained as precipitates, while prothrombin, plasmin and other proteins were washed off. Together with Inga Marie Nilsson, a young scientist and physician from Malmö General Hospital, Margareta found that factor VIII could be almost completely recovered from this fraction designated “Cohn’s fraction 1-0” [@Nilsson-57-AMS]. A sterile preparation of fraction 1-0 was injected for the first time to Inga Marie’s patient in May 1956 at the Malmö General Hospital. The patient was a young female patient with life-threatening menstrual bleeds and a prolonged bleeding time (i.e. with severe von Willebrand disease). The girl’s bleeding stopped promptly, her Factor VIII activity increased to a high level and her bleeding time was normalized. After this, the Blombäcks began preparing Fraction 1-0 from plasma for PWHs with impressive efficacy. Industrial production of Fraction 1-0 by Kabi pharmaceuticals was started in 1964. Calling the product AHF (antihemophilic factor), Kabi became one of the two first commercial producers of Factor VIII concentrates in the world. For more detailed description on the history of factor VIII discovery and production see also Ahlberg et al [@Ahlberg-65-JBJS].

Although this first AHF concentrate was of low purity and contained large amounts of fibrinogen, it was used for many years to treat hemophilia and, as it also contained von Willebrand activity, for treating von Willebrand disease. Indeed, the introduction of Fraction 1-0 led to effective hemophilia care in Sweden, a decade earlier than in most other countries. It was only about 10 years after Inga Marie’s initial injection that effective therapy started elsewhere using cryoprecipitate. During the 1970’s and 1980’s increasingly more concentrated products were produced, and when the injection volume decreased the freeze-dried factor concentrates became available for home treatment.

Until the mid-1980s, before virus inactivation of cryoprecipitate and later plasma-derived coagulation factor concentrates, there was a high rate of hepatitis B and C and, in the late 1970’s and early 1980’s, of HIV transmission in PWHs. Most PWHs were infected with HBV, some with HCV, but none with HIV were able to clear the virus. Close to 90% of severe PWHs receiving plasma derived factor concentrates before year 1986 in the Western world were infected with HIV and AIDS was a major cause of morbidity and mortality in PWHs in the 1980’s and 1990’s before effective treatment was available. Hepatitis C has since become curable with modern drug treatment in most cases. Due to the use of locally produced plasma derived factor VIII concentrates in Norway only 14 patients were infected with HIV, in Finland only two patients and in Iceland none were infected. However, hepatitis C was transmitted to about 30-60% of patients in Norway, Finland and Iceland. Figures in Sweden reached just above 80%. Since 1986 all available plasma derived and recombinant concentrates have been virus inactivated preventing transmission of the above encapsulated viruses and, fortunately, no hepatitis B, C or HIV transmission has occurred. Nevertheless, patients and care-givers alike remain concerned that the current measures to eliminate viruses could not entirely prevent transmission of known and unknown non-encapsulated viruses and prions, e.g. variant Creutzfeldt-Jacob disease [@Mannucci-08-HAE].

Prophylactic factor replacement therapy has led to a dramatic improvement in the orthopedic outcome of PWHs in Sweden and the Nordic countries [@Nilsson-92-JIM]. The value of costly prophylactic therapy was not generally recognized outside the Nordic area until many decades later when a prospective randomized trial finally conducted demonstrated the markedly improved clinical outcome of boys receiving early prophylaxis [@Manco-07-NEJM]. Data from Malmö has shown that not only the joint score but, importantly, the overall quality of life of PWHs treated with prophylaxis in Malmö has close to normalized, in particular in those patients who have been treated with primary and continuing prophylactic therapy [@Khawaji-12-EJH].

Currently, all Nordic countries practice primary prophylaxis in severe hemophilia using preferably recombinant products.
