# Inhibitors

#### Revision by: Jan Astermak (Malmö) and Fariba Baghaei (Gothenburg) {-}

## Introduction

The development of antibodies is a serious complication of factor replacement therapy. The antibodies bind to the factor VIII or IX molecule and in many cases neutralize (inhibit) the hemostatic efficacy. The incidence of inhibitory antibodies in patients with severe hemophilia A is about 30%, whereas less common in patients with a milder form of the disease. Among persons with hemophilia B, inhibitors are less frequent and usually <5%.

The formation of inhibitory antibodies is a complex immunological process involving both genetic and non-genetic factors [@Astermark-14-HAE]. Due to its complexity, an evidence based approach to base the clinical management of patients on is difficult to achieve, but clearly genetic factors including first of all the type of causative mutation and HLA but also several immune response genes will have an impact. In addition, the intensity of treatment with higher doses over several days has been defined as a risk. Only one randomized study has been published with the aim to evaluate one of the potential non-genetic risk factors i.e. the type of concentrate [@Peyvandi-16-NEJM]. In this study, in which the cohort of PUPs and MTPs was more or less equally split between prophylaxis and on-demand treatment, plasma-derived factor VIII was associated with less inhibitors. However, in the case of high-titer inhibitors, no significant difference was observed. Even though the data are of interest, several issues remain to be settled and the decision on which product type to use in the individual case, should be based on safety, efficacy and availability in an open dialogue with the family. In addition, the inhibitor incidence with the new EHL molecules in PUPs is not yet available.

The presence of an inhibitor is confirmed using the "Bethesda inhibitor assay" with Nijmegen modifications and classified according to the peak titer into "high" (>5 BU/mL) or "low responding" (<5 BU/mL). The antibodies usually appear within the first 50 treatment doses, but may occur throughout life.

Inhibitory antibodies at low titer can be overcome by saturating levels of the deficient factor, whereas bleedings in patients with high titer need to be treated with "bypassing agents". These agents will not be affected by the factor VIII or IX inactivating antibodies but induce hemostasis. There are two bypassing agents currently available in Nordic countries; one plasma-derived activated prothrombin complex concentrate (aPCC) and one recombinant coagulation factor VIIa (rFVIIa). These agents are also used in inhibitor patients for the cover of surgical procedures and in the prevention of bleeds (prophylaxis). The most favorable option for inhibitor patients is the eradication of the inhibitor by immune tolerance induction (ITI) therapy. In this therapy, regular infusions of factor concentrates (factor VIII or IX) are administered (usually daily and at high doses) for weeks to years with or without immune-modulating drugs. We recommend that the ITI should be performed according to an international protocol and the patients should be recruited to international studies whenever possible.

## Bypassing agents for the treatment of bleeds

### Recommendations {-}

*	FVIII and FIX should be used as the first option in patients with a current low inhibitor titer, in order to saturate the inhibitor and reach a hemostatic factor level. In the case of life-threatening bleeds, irrespective of inhibitor response, FVIII/IX:C should be monitored at least daily. The risk of allergic reactions associated with FIX concentrates should be taken into consideration.

*	The use of bypassing agents at the doses of aPCC 50-100 IU/kg every 6-12 h or rFVIIa 90-120 $\mu$g/kg every 2-3 h is indicated for patients with inhibitor levels >5 BU/mL for treatment of any bleed and in those with high-responding inhibitors but a current low level (<5 BU/mL) in case of a non-life-threatening bleed. Children may need higher doses up to 270 $\mu$g/kg of rFVIIa as an initial dose followed by lower doses depending on the hemostatic effect.

*	rFVIIa is preferred in patients with a known anamnestic response prior to start of ITI, as well as in patients previously not being exposed to plasma products.

*	Antibody removal by immunoadsorption might be considered in patients with high inhibitor titers in order to allow treatment with FVIII/IX concentrates.

*	Concurrent use of tranexamic acid should always be considered with rFVIIa treatment, but also in association with aPCC to improve the hemostatic effect.

*	Higher doses of rFVIIa (up to 270 $\mu$g/kg) and/or shorter intervals (<2hrs) should be considered in young children and in the case of treatment failures.

*	The daily dose of aPCC should routinely not exceed 200 IU/kg.

*	In hemophilia B patients with inhibitors, rFVIIa is preferred. FIX-containing agents e.g. aPCC should not be routinely used.

*	In the case of bleeds resistant to monotherapy with each bypassing agent, a sequential use in the order of aPCC (50-75 IU/kg) and rFVIIa (90-100 $\mu$g/kg) with an interval of $\geq$ 2 hrs or a combined use of aPCC (20-30 IU/kg) and rFVIIa (30-60 $\mu$g/kg) may be considered. The risk of thromboembolic complications however always needs to be taken into account. 

Most of the studies of rFVIIa and aPCC are retrospective and observational with low scientific value if one applies strict scientific criteria, but both agents have shown to be effective in the majority of cases. One drawback using these drugs is the cost. Therefore, the treatments with rFVIIa and aPCC need to be optimized to the extent possible. Two randomized head-to-head-studies have been conducted showing a similar high hemostatic effectiveness with both products. However, a difference in efficacy was observed with the respective products in one and the same patient, suggesting that predictive markers for the treatment response need to be identified [@Young-08-HAE; @Santagostino-06-JTH].

The randomized study by Young et al [@Young-08-HAE] compared not only rFVIIa with aPCC, but also two treatment doses of rFVIIa in a blinded design. The results suggest in accordance with other case series and cohort studies, that rFVIIa can be administered at a dose of 270 $\mu$g/kg on a single occasion, instead of three doses of 90 $\mu$g/kg, without reducing the efficacy or exposing the patient to risk [@Santagostino-06-JTH].

The mechanisms of action differ between aPCC and rFVIIa. Therefore, a sequential or combined use of them has been studied and suggested to improve efficacy [@Schneiderman-07-HAE]. The risk of thromboembolic complications however always needs to be taken into account [@Ingerslev-11-BJH], in particular in patients with a central venous access device, and the parallel use of them used cautiously and for the time being only in resistant cases. An algorithm for the use of aPCC and rFVIIa has been defined [@Teitel-07-HAE].

## Prevention of bleeds

### Recommendations {-}

*	Prophylaxis with rFVIIa (90 to 270 $\mu$g/kg) once daily intravenously, aPCC (85 IU/kg) every other day intravenously or emicizumab subcutaneously (3 mg/kg for 4 weeks followed by 1.5 mg/kg weekly) should be considered in patients with inhibitors following a severe/life-threatening bleed and/or repeated bleeds requiring by-pass therapy before, during or after ITI with or without immunesuppression. **Note that Emicizumab will only be an option for patients with hemophilia A.**

*	In patients with ITI-failure emicizumab might be considered as the first choice treatment for prevention of bleeds.

*	For treatment of break through bleeds requiring additional hemostatic drug intervention during prophylaxis with emicizumab, rFVIIa should be used as first-line option and the initial dose of rFVIIa should not exceed 90 $\mu$g/kg. Doses of 45 and 90 $\mu$g/kg at a dose interval of 2 to 4 hours may be considered. Due to the hemostatic effect of emicizumab, the number of doses of rFVIIa should be minimized.

*	If aPCC and emicizumab together will be required as second line treatment and/or resistant severe bleeds, the initial dose of aPCC should not exceed 50 U/kg. Then, if a second dose of aPCC is considered, the patient should be referred to the hospital for treatment and surveillance for TMA. The total dose of aPCC should not exceed 100 U/kg/d and - as a routine - not provided for more than 24 hours per treatment episode. The recommendation regarding by-pass therapy together with emicizumab should be followed for 6 months after the infusion of emicizumab.

*	For all three prophylactic agents, a hemostatic improvement of the bleeding phenotype should be required defined as a reduction in the number of significant bleeds with $\geq$ 50%.

Bypassing agents have for several years been used to prevent bleeds in patients with inhibitors. This is a costly treatment, but should be considered in persistent inhibitor patients and/or phenotypic bleeders to protect against harmful bleeds while waiting for the inhibitor to become eradicated. Recently, another option for the prevention of bleeds, emicizumab, was approved for subcutaneous administration by the FDA and EMA in patients with hemophilia A and inhibitors ($\geq$ 12 years). In the case of the previously used two bypassing agents, i.e. aPCC and rFVIIa, no head-to-head comparison has been performed, but available data show that both drugs can be used prophylactically to reduce the number of bleeds [@Konkle-07-JTH; @Leissinger-11-NEJM; @Antunes-14-HAE]. A reduction in the bleeds up to approximately 60% have been reported for rFVIIa in daily doses of 90 to 270 $\mu$g/kg and up to around 70% with aPCC in the dose of 50 to 85 U/kg 3 times weekly or every other day.

Emicizumab, is a humanized antibody that bridges activated FIX and FX, mimicking FVIII function. A total of 169 haemophilia A patients with inhibitors, 12 years of age or older, were enrolled in the pivotal study. Patients were given 3 mg/kg once-weekly for 4 weeks followed by 1.5 mg/kg weekly thereafter. Emicizumab prophylaxis (s.c) had 87% lower bleeding rate (treated bleeds) than patients with no prophylaxis (p<0.001). The ABR was 2.9 events in prophylaxis group versus 23.3 events in participants with no prophylaxis. Participants who had previously received prophylactic treatment with bypassing agents were also enrolled and switched to emicizumab prophylaxis, which resulted in a lower bleeding rates (treated bleeds) compared to previous prophylaxis with bypassing agents, but these figures cannot be directly compared [@Oldenburg-17-NEJM].

Bypassing agents (rFVIIa or aPCC) were used for treatment of bleeds.

The most reported adverse events were injection-site reactions. Thrombotic microangiopathy (TMA) and thromboembolic events were reported among 5 participants after treatment with aPCC with average doses of more than 100 U/kg daily for more than one day.

In patients with low-responding inhibitors, prophylaxis with the deficient factor can be used to prevent against bleeds as well as potentially induce tolerance.

Other non factor replacement strategies such as anti-TFPI and RNAi therapeutic antithrombin (Fitusiran) and zymogen like FXa might have a potential for management of haemophilia patients with inhibitors in future, but these agents are not yet available for routine clinical use [@Nogami-19-BLOOD].

## Immune tolerance induction (ITI) therapy

### Recommendations

*	The principal goal in all patients with inhibitors should be to eradicate the immune response and to tolerize the patient.

*	All children with confirmed low-responding inhibitor should continue on regular replacement therapy to induce tolerance.

*	Adults with a low-responding inhibitor should if persistent and, preferentially if bleeds are not successfully treated on demand with the deficient factor, be offered regular replacement therapy to induce tolerance.

*	Children with high-responding inhibitor, but no bleedings may wait with ITI until decline of the inhibitor - preferentially below 10 BU/mL. In case of bleedings, ITI should however be started immediately.

*	Adult patients with high-responding inhibitors should be offered ITI as for children.

*	A high factor dose seems to reduce the time to reach a negative inhibitor titer, and since bleeds mainly occur during this period, a dose of 100-200 IU/kg/d should be first-line option whenever possible. Lower dose may however be used with a similar final outcome – at least in so called good risk patients.

*	No consistent data indicate the beneficial use of one type of product over the others, but in patients who fail the initial attempt of ITI with high purity FVIII, a VWF-containing FVIII concentrate should be considered. The potential role of EHL products for tolerization in resistant cases is currently not known.

*	Switch of ITI protocol or discontinuation of ITI should be considered when no further significant decline or improvement in clinical phenotype has occurred for 4-6 months.

*	In resistant cases and in poor risk patients as well as in adults, the combined use of the deficient factor and immunosuppression should be considered - even as first-line treatment in adult patients.

*	In patients with hemophilia A and resistant high-responding inhibitors failing ITI protocols with and without immunosuppression, ITI may be stopped and emicizumab provided prophylactically for bleed protection.

*	Immunosuppression may be considered as a first-line option in patients with hemophilia B and a causative gene defect such as a gene deletion and/or nonsense mutation.

*	After successful tolerance the dosing should be tapered to regular prophylactic treatment.

*	In patients with mild/moderate hemophilia, the possibility of spontaneous remission ($\approx$ 20%) should be taken into consideration and a watch and wait strategy might be advisable before treatment. If persistent, immunosuppression e.g. Rituximab should be considered as a first line option with or without the combined use of the deficient factor based on the bleeding phenotype of the patient.

ITI treatment with the intent to induce tolerance was described in the 1970s and should be the ultimate goal when possible in all patients with a persistent inhibitor to reduce the risk of harmful bleeds. Successful treatment also has a cost-saving potential [@Rocino-16-HAE]. The principle mainly consists of a repeated exposure for the deficient factor with or without the concomitant use of immunosuppressive agents. Several different regimens have been described, many of which seem to have a similar outcome. A decline of the pre-ITI titer to low levels and a low peak before or during ITI seems to mirror a beneficial immune response. One randomized study has so far been conducted - in patients with "good risk" severe hemophilia A and high titer inhibitors comparing high (200 IU/kg/d) and low dose (50 IU/kg 3 times/week) FVIII. No difference in success rate (about 70% in the intention-to-treat analysis) between the treatment arms was seen. However, the time to achieve a negative titer, i.e. the phase with most frequent bleedings, was significantly shorter with the high dose regimen [@Hay-12-BLOOD].

The other non-randomized studies reported in the literature are difficult to compare since the agents, doses, dose intervals, and definitions of tolerance vary. However, most of the retrospective analyses show tolerance to be induced in up to 60-80% of the cases regardless of the type of agent and dose [@Rocino-06-Haem]. A higher efficacy rate of von Willebrand-containing FVIII products to induce tolerance compared with more highly purified products has been suggested in patients with unfavorable prognosis [@vanVelzen-14-BJH]. However, additional studies and data are needed to confirm these findings and whether product type including the new EHL products will impact success rate is still not settled.

### ITI and mild/moderate hemophilia

In hemophilia A, up to 25% of new inhibitors occur in patients with mild or moderate disease and changes the bleeding phenotype from mild/moderate to severe [@Darby-04-JTH]. Inhibitors most commonly arise following an intensive episode of replacement therapy for surgery or major trauma. The risk of inhibitor development also appears to be associated with some high-risk factor VIII gene mutations [@Eckhardt-13-BLOOD]. The limited data available in patients with non-severe hemophilia A suggests that when treatment is used, strategies that modulate the immune system, such as the use of rituximab may have greater benefit than ITI performed with only the deficient factor, but additional studies are needed to confirm these findings. Importantly, the inhibitors might be transient and disappear spontaneously. Therefore, the necessity of eradication treatment should be critically examined for each individual patient [@Kempton-12-AJH].

### ITI and hemophilia B

ITI treatment in hemophilia B seems to be associated with a less successful outcome compared with hemophilia A. The reasons for this are not known. In addition, the procedure is, in some cases, jeopardized by the occurrence of an allergic/anaphylactoid reaction and nephrotic syndrome. The use of ITI in these patients therefore needs careful monitoring and should initially be provided in the hospital setting. To reduce the exposure for the deficient factor IX molecule, lower dose and immunosuppressive drugs should be considered, such as the use of steroids, rituximab, cyclophosphamide, cyclosporine, mycophenolate mofetil and/or other agents [@Berntorp-00-Haem; @Beutel-09-Hamost].
