# Laboratory diagnosis 

#### Revision by: Karin Strandberg (Malmö) and Genetic diagnosis by Rolf Ljung (Malmö) {-}
#### Reviewed by Carola Henriksson (Oslo), Jovan Antovic (Stockholm) and Timea Szanto (Helsinki) {-}

### Recommendations {-}
*	The global test APTT will usually be prolonged and can be used as screening test in haemophilia A and B. The factor sensitivity for different APTT-reagents varies.

* Factor VIII:C and IX:C, functional activity assays can be measured with either one-stage clot-based (OSA) or chromogenic method (CSA). Assay discrepancies can be caused by different mutations but also analytical factors. OSAs are generally more prone to interferences.

*	Nijmegen-Bethesda assay is the recommended method for neutralizing FVIII or FIX antibodies. It is most reliable in patients without measureable factor activity (ie severe haemophilia).

*	Discrepant results between OSA and CSA (difference of 20-30%) exists and are generally accepted when postinfusion levels of rFVIII or rFIX products are monitored.

*	For more than one modified EHL-product, a difference larger than 30% has been obtained between different OSAs or between OSA and CSAs.

*	For diagnostic and monitoring purposes, it is therefore of importance that the laboratory has access to more than one method for FVIII:C and FIX:C, respectively. Preferably one CSA and one OSA method.

## Pre-analytical aspects of hemophilia testing

The pre-analytical phase is often equal with the time from the blood collection to the point when the sample is analyzed in the laboratory. Errors at this phase are often explained by incorrect specimen collection, handling, transportation or storage. Important aspects are also the blood sampling technique. Especially: Underfilling of tubes or presence of clots due to incorrect mixing, might lead to rejection of samples. The presence of anticoagulants in the sample, for example heparin contamination from a vascular access device, may interfere in the assay and give false test results. In order to reduce the pre-analytical error rate, it is important to understand the sources of variability and mechanisms that may lead to false assay results. Coagulation tests are exceptionally susceptible to suboptimal sample quality as the sample collection itself will initiate a hemostatic response. Thus, improper sample collection technique and/or incorrect handling prior to analysis will increase the risk of having the coagulation system activated to such an extent that the results of screening and specific factor assays can lead to mismanagement of the patient. This is particularly true for hemophilia testing as FVIII is one of the most labile coagulation factors and is degraded with time *in vitro*.

There are published guidelines/recommendations, how to assure sample integrity during the pre-analytical phase [@Adcock-08-CLSI; @Adcock-13-QLHT].

### For plasma-based coagulation assays the recommendation is:

*	Direct venipuncture: Ensure atraumatic phlebotomy with minimal tourniquet use.

*	Collection tube and order of draw: 3.2 % (109 mmol/L sodium citrate, light blue stopper) first or only after a non-additive tube for screening and specific coagulation factor analyses.

*	Fill tube correctly to the mark (line).

*	Adequately and thoroughly mix with anticoagulant (reverse tube immediately 5-10 times).

*	Transport the whole-blood promptly at room temperature.

*	Centrifuge within 1 hour of phlebotomy to obtain platelet poor plasma (<10 x 109/L).

*	If testing can not be performed within four hours, the plasma should be transferred by pipetting to another tube and frozen at -70$^\circ$C for later analysis.

## Screening for hemophilia

Coagulation screening assays, i.e. activated partial thromboplastin time (APTT) and prothrombin time (PT), are important for the initial laboratory evaluation of patients with bleeding disorders and are available in most hospital laboratories. If congenital or acquired hemophilia A or B is present, the APTT will usually be prolonged and the PT (INR) remains within normal limits. Furthermore, in congenital hemophilia the APTT will be corrected when patient plasma is mixed 1:1 with normal plasma [@Kitchen-10-LM]. If mixing does not correct the prolongation it may indicate the presence of an inhibitor (against a coagulation factor or lupus anticoagulant) or other anticoagulant present in the plasma. There are several commercially available APTT reagents that vary in their sensitivity for coagulation factor deficiencies. Some reagents are relatively insensitive to lupus anticoagulant and these may be advantageous. To be accepted for factor-deficiency screening, it is recommended that the APTT reagent in use should give a prolonged clotting time at a factor activity of $\leq$ 30% [@Kitchen-10-LM]. It is also important to understand that the APTT is a global plasma assay that depends on the sum effect of 10 different coagulation factors and low FVIII or FIX levels, compatible with mild hemophilia A or B, may be masked by increases of one or several of the other factors during certain conditions such as an acute phase reaction, resulting in a normal APTT. Thus, it is important that the treating physicians are familiar with the local screening methodologies and reference intervals. 

## Specific Factor VIII and IX assays

FVIII:C or FIX:C in plasma represents the functional (coagulation) activity of the factors and can be measured with either clot-based or chromogenic assays [@Kitchen-10-LM; @Peyvandi-16-JTH].  These analyses are important in the diagnostic setting, during therapy (measurement of trough and peak levels after administration of replacement products) and also to detect the presence of inhibitory antibodies. When a family history is present, umbilical cord blood is tested in male infants at birth to determine FVIII or FIX levels. For prenatal diagnosis, see chapter “Carriers of hemophilia”.

The FVIII:C and FIX:C assays should be calibrated with material that has traceability to current international standard for FVIII or FIX in plasma [@Kitchen-10-LM]. In this way the unit is given in international units (IU) and one IU is the factor activity present in one mL of normal plasma. In most of the Nordic countries the results are given in kIU/L or IU/mL but in the Anglo-American sphere it is common to use IU/dL (IU/dL, the same as percentage in absolute numbers; ie 5 IU/dL= 5%).

### Differential diagnosis

Once a decreased FVIII level has been confirmed, the differential diagnosis includes congenital hemophilia A, acquired hemophilia A and von Willebrand disease (VWD), type 2N VWD (Normandy) in particular. Appropriate investigation to sort this out includes the case history and inheritance pattern, bleeding score, ruling out the presence of lupus anticoagulant, measuring antibodies against FVIII and VWF activity, and, when appropriate, the VWF:FVIII binding which determines the FVIII binding capacity of patient's VWF. Definite diagnosis may be dependent on sequencing of the F8/9 and VWD genes.

### Factor VIII:C assays

The one-stage assay (OSA) is the most frequently used assay principle in the world [@Kitchen-10-LM; @Peyvandi-16-JTH]. The main feature of the OSA is that it is based on the APTT test with the difference that the sample is pre-diluted in FVIII-deficient plasma before analysis. In this way, a test system is created that works with the simplicity of the APTT reaction but the pre-dilution procedure makes the FVIII activity in the sample the limiting factor and thus determines the final clotting time. The ability of the sample to correct the APTT of a FVIII-deficient plasma can be expressed as the FVIII:C activity if the assay is calibrated with a plasma with known concentration of FVIII:C.

The performance of the OSA is affected by the type and quality of the APTT reagent and the FVIII-deficient plasma used. The FVIII-deficient plasma can be obtained from a patient with severe hemophilia A (<0.01 kIU/L and without antibodies) or be immunodepleted. It is important to verify that new lots of FVIII-deficient plasmas are free from FVIII (<0.01 kIU/L) as this otherwise will compromise the test. Also, normal VWF concentrations of the FVIII-deficient plasma may be an advantage. According to the discussion about the APTT reagent above, the choice of APTT reagent will also have an impact on the general assay characteristics. It is important that the laboratory choose reagents that have proven capacity to detect all hemophilia categories i.e. mild to severe hemophilia A. The results obtained by OSAs may be affected by the presence of lupus anticoagulant, heparins, etc.

Another version of the FVIII:C assay is the chromogenic substrate assay (CSA). The assay procedure involves two separate reactions in a way that makes FVIII:C in the sample being the rate-limiting factor. There are several commercial kits available for CSA of FVIII:C in which the end product is colour development from generation of activated FX that cleaves a chromogenic substrate. In the first step the diluted sample (or standard) is mixed with a reagent cocktail with purified factors IXa, X and phospholipids, leading to the formation of FXa. In the second step a specific chromogenic substrate for FXa is added. Cleavage of the substrate yield a colour formation that is recorded spectrophotometrically. The amount of colour development is directly proportional to the FVIII:C activity in the sample. In general, the CSA has a lower detection limit than the APTT-based OSA and, due to the high dilution factor of the sample, the influence of interfering substances is less. This assay is common among the Nordic hemophilia centers. The chromogenic assay is also used by the pharmaceutical industry when the potencies of FVIII concentrates are assigned.

The different FVIII:C assays should give similar results in most cases. However, in approximately 20% of genetically confirmed mild/moderate hemophilia A patients there is a significant assay discrepancy between OSA and CSA, with OSA FVIII at least 2-fold higher than CSA levels. Furthermore, patients with certain mutations in the F8 gene causing mild hemophilia A may be missed using the OSA FVIII assay. In general, the clinical phenotype corresponds better to the results of the CSA compared to the OSA. Also, there are some genotypes causing inverse assay discrepancy, with lower one-stage assay results in mild hemophilia A. Thus, mild hemophilia A may be challenging to identify correctly in the laboratory, if only one of the assay principles are used. For the management of hemophilia A, both OSA and CSA should be performed to ensure detection of all new mild/moderate cases and to correctly assess the severity [@Pavlova-14-TH; @Bowyer-13-Haem]. 

*Reference interval*: Usually between 0.50-2.00 kIU/L, but local differences may apply.
*Interpretation*: Hemophilia A patients have low FVIII:C levels. Levels <0.01 kIU/L are seen in severe hemophilia A. Moderate deficiency is characterized with FVIII:C levels between 0.01-0.05 kIU/L and patients with mild deficiency have levels from > 0.05 kIU/L up to 0.40 kIU/L. Carriers of hemophilia A have usually approximately 50% of the normal activity but can occasionally have levels in the mild hemophilia range leading to increased bleeding. FVIII is an acute phase reactant and the levels of FVIII may increase several fold under certain conditions (e.g. trauma, infection, etc).

### Factor IX:C assays

The principle of OSAs for FIX is similar as for FVIII described above, with the only difference that the sample is prediluted in FIX-deficient plasma before analysis. Thus, the main FIX:C assay principle is a test system based on the APTT with dilution of the sample (patient or standard plasma) in a plasma lacking FIX, which means that the activity of FIX in the sample is the limiting factor. The assay is calibrated with a standard that is traceable to the current international standard of FIX:C in plasma and results expressed as kIU/L (see FVIII:C above).

Chromogenic FIX:C assays have become commercially available and is an alternative to the OSA. However, these assays are offered by few laboratories and have not yet been fully approved by regulatory bodies (EMA) for potency labelling. Nevertheless, local implementations in Nordic and other laboratories are encouraging and it is likely that these assays will display analytical advantages compared to the OSA as has been shown for the CSA for FVIII:C. Assay discrepancy, caused by mutations in the F9 gene, has been recently described also in hemophilia B [@Kihlberg-17-HAE].

*Reference interval*: Usually around 0.60-1.50 kIU/L but local differences may apply.
*Interpretation*: Congenital deficiency of FIX is the cause of hemophilia B. Acquired hemophilia B, caused by specific inhibitors exists but is less frequent than the rare acquired hemophilia A. The degree of the deficiency defines the different forms: Severe haemophilia B with FIX:C <0.01 kIU/L; moderate deficiency with FIX:C between 0.01- 0.05 kIU/L and mild deficiency with levels from >0.05 up to 0.40 kIU/L. Carriers of hemophilia B express about 50% of the expected normal FIX:C activity. 

### Antibodies against FVIII or FIX

The hallmark of neutralizing anti-FVIII or anti-FIX antibodies (=inhibitors) is a prolonged APTT and normal PT (INR). The prolongation of the APTT is persistent also after mixing of the patient sample with an equal volume of pooled normal plasma. Alloantibodies are most frequent and have a fast and dose-dependent antigen-antibody reaction. In acquired hemophilia A, time-dependent autoantibodies with a low binding affinity can be present. For this reason, it is recommended to incubate the samples for two hours at 37$^\circ$C during a mixing experiment in order to allow the antibody to have effect. Anti-FIX antibodies have faster kinetics and it is usually not necessary to incubate longer than 10 minutes. For anti-FVIII antibodies it is also important to use buffered pooled normal plasma (ie HEPES) as this stabilizes the pH and thus the FVIII activity during the incubation and this will reduce the risk of obtaining false positive results.

The recommended test procedure for quantitation of the inhibitor titer is the Bethesda-Nijmegen mixing test, which is an assay for inhibitory antibodies [3]. In brief, a test sample is prepared by mixing equal volumes of patient plasma with normal plasma and then measure the residual factor activity in the plasma mixture after 2h incubation. A control sample is prepared in parallel with pooled normal plasma mixed with an equal volume of FVIII-deficient plasma. Both test and control samples are incubated for 2 h at 37$^\circ$C and then the factor activities in both samples are measured. There is usually a good correlation between the inhibitor results based on the OSA and CSA FVIII:C assays [@Potgieter-15-EJH, @Miller-18-HAE]. Any residual activity in the sample between 25 and 75% can be used for calculations of the inhibitor titer. By definition, one Bethesda unit (BU) is the inhibitor titer that neutralizes 50% of the factor activity in one mL plasma. If the residual activity is less than 25% it indicates an inhibitor titer above 2 BU/mL. Hence, these samples are prediluted in FVIII-deficient plasma before analysis until a residual activity within the 25-75% range is reached. The final inhibitor level is then calculated by multiplication with the dilution factor. If several dilutions result in residual activities in the 25-75% range then the dilution that is closest to 50% is chosen for calculation of the inhibitor titer. It is recommended to perform the Bethesda assay when there has been a washout of the concentrate (ie FVIII < 0.1 IU/ml) [@Miller-18-HAE].

Reference interval: The cut-off for a positive result is by definition 0.4 BU/mL, as the recommendation was not to use any residual activity above 75% (75% residual activity corresponds to 0.4 BU/mL).  Many laboratories instead use 0.6 BU/mL as the cut-off for positivity as the test is less reliable in the low titer range (reduced risk of false positive results).

*Interpretation*: The presence of inhibitors may be suspected in patients with unexpected bleedings despite regular prophylaxis. This is also strengthened if the patient displays reduced recovery and half-life of the substituted factor. Patients with acquired haemophilia have very different clinical symptoms, caused by autoantibodies against factor VIII or IX.

Note: The Bethesda assay is usually performed on patients with severe type of hemophilia that do not have measurable FVIII:C (or FIX:C) activity. If the patient has an activity of 0.10 kIU/L or higher this must be taken into consideration when the inhibitor titer is calculated. It is also possible to remove the endogenous activity by heat-inactivation of the plasma sample at 56$^\circ$C before analysis [@Miller-18-HAE]. The FVIII-mimetic emicizumab interferes with inhibitor measurements in clot-based assays, but a chromogenic assay with bovine reagents can be used.

### Factor activity assays for monitoring treatment with factor concentrates with focus on EHL-products

For monitoring postinfusion levels of full length rFVIII standard products, CSA results are generally reported to be about 20% higher than OSA results. Well-documented discrepancies have also been described for B-domain deleted rFVIII (Refacto®), with results 30% higher for CSA than OSA. Calibration with B-domain deleted FVIII has therefore been recommended for OSA. For rFIX products, CSA results are instead in general 30% lower than OSA results [@Peyvandi-16-JTH; @Kitchen-17-STH].

There are a number of products modified for an extended half-life (EHL), both rFVIII and rFIX, recently on the market or under development (i.e. pegylated, glycopegylated, and fusion proteins) (See Chapter Prophylaxis) [@Peyvandi-16-JTH]. Some of the modifications affect factor assays and can result in under- or overestimation of results in postinfusion patient samples, which might have a potential impact on patient management. The European Pharmacopoeia (8th ed. 2016) recommends the use of CSA for replacement factor potency labelling of FVIII and OSA for FIX. The FVIII and FIX sub-committee of the Scientific and Standardization Committee (SSC) of the International Society on Thrombosis and Haemostasis (ISTH) recommendation is that if either the OSA or the CSA for FVIII activity provides valid potency estimates relative to the WHO IS for concentrates, this assay can be used for potency labelling [@Hubbard-13-JTH; @Dodt-15-HAE]. If both methods provide valid potency estimates, either assay can be used for potency labelling and if there are discrepancies between assays, the most appropriate assay for labelling must be identified. This issue has also been addressed by the European Medicines Agency (EMA) [@Adcock-18-IJLM]. Ideally, similar recovery results should be obtained in post-infusion samples with the same method as used for potency labelling.

For more than one of the modified products, a difference of > 30% has been obtained for factor levels when different APTT-reagents have been used in different OSAs [@Kitchen-17-STH; @Adcock-18-IJLM]. All reagent-product combinations have not been tested, and all reagents that contain the same activator (ellagic acid/phenol, silica/kaolin type) do not give the same results. More adequate factor levels are generally obtained with the chromogenic methods. However, it is a challenge that field studies with comparable data for different modified products still are lacking. Both ECAT and UK NEQAS (European external quality control providers in haemostasis) are performing larger field studies, and generalized product-by-product-based guidance about systematic under- or overestimation of activity for many reagent combinations can hopefully soon be given.

A possibility could be to use product-specific reference standards. For example, the use of a B-domain deleted rFVIII laboratory standard was previously shown to reduce the discrepancy between one-stage and chromogenic assays, allowing a more accurate assessment of FVIII activity levels in patient plasma samples [@Adcock-18-IJLM]. This is perhaps a more theoretical than practical option. It is very cumbersome for the laboratory to validate such laboratory-developed tests for product-specific standards, and thus such assays might only be available at very few specialized central laboratories. It also requires that the laboratory is informed about the type of product used in every patient. The risk for miscommunication to the laboratory is evident.

Another possible approach to avoid incorrect measurements of modified rFVIII and rFIX products in post-infusion plasma samples would be for the manufacturers to provide information about the most suitable assays (i.e., reagent-instrument combinations) for treatment monitoring of specific products. The manufacturers should also give information about where patient samples can be sent for testing using the appropriate reagents for the replacement product used. However, this is a strategy that can not be used in emergency situations.

Other options that are now beginning to be used in clinical routine settings, are other global coagulation tests, such as viscoelastic coagulation methods (ROTEM®, TEG®) and thrombin generation (CAT®, Ceveron alpha®), that can, if available, be used as a complement for monitoring purposes of certain products.

For the management of hemophilia patients with EHL-products, it is important that the laboratory has access to more than one method for FVIII and FIX respectively, preferably one CSA and one OSA method. With the information available it seems the chromogenic method is the more consistent laboratory method that can adequately measure the levels of most EHL-products.

In conclusion:

*	Modified rFVIII and FIX replacement products show significant APTT-reagent dependent recovery in OSA, whereas the recovery is more consistent in CSA.

*	There is only limited comparable data from field studies comparing several EHL-products in OSAs with various combinations of reagents, including also the CSAs commercially available in the same study, from which generalized product-by-product-based guidance about systematic under- or overestimation of activity can be given.

*	Ideally, similar recovery results should be obtained in post-infusion samples with the same method as used for potency labelling and these data must be available from the manufacturers of the products.

*	A significant challenge to the laboratories and also to clinicians will be to communicate to the laboratory the specific factor replacement product used by each patient.

## Genetic diagnosis

Genotyping is clinically useful to predict the risk to develop inhibitor and for carrier- and prenatal diagnosis. For a detailed description of the genetic diagnosis of hemophilia, we refer to the UKHCDO 2015 document "Guideline on Clinical Genetics Services for Haemophilia" of the UK Haemophilia Centre Doctors’ Organisation (UKHCDO) [@Keeney-10-CMGS]. Depending on the experience and competence of the hemophilia team and the local organisation of genetic services, a clinical geneticist or counsellor can be part of the hemophilia care team.

Genetic diagnosis of severe hemophilia A starts with screening for the intron 22 inversion of the F8 gene which is caused by homologous recombination involving intron 22 and related sequences outside the F8 gene [@Lakich-93-NG]. Approximately 40% of cases of severe hemophilia A is caused by intron 22 inversion. Similarly, an inversion involving intron 1 has also been discovered in 1-2% of severe cases which can also be screened for with a PCR technique. In the remaining cases of severe hemophilia A as well as all other cases the whole F8 gene, 26 exons, must be sequenced since most patients have their own unique mutation. Mutations such as nonsense and deletions, “null-mutations”, will obviously cause severe hemophilia since the DNA reading frame will be altered, mRNA aberrant and protein will not be synthesized. A missense mutation will usually produce a dysfunctional protein with reduced clotting activity but may also result in a 'neutral mutation' or a polymorphism. In such cases it is important to know if the same mutation has been reported previously in patients with hemophilia, in databases such as 'FVIII variant Database' [@FVIIImutDB], or 'CHAMP' and 'CHBMP' databases [@CDCmut]. One may also use various mutation prediction programs to evaluate the deleterious effect of a mutation. In a few percentage, mutations will not be found despite sequencing of the whole gene, some of these cases having a more complex genetic background. The MLPA technique may reveal deletions or duplications.

In hemophilia B, the 8 exons of the F9 gene are sequenced and in almost all cases the mutation will be found. Inversions are not present in the F9 gene but some patients have complete gene deletions, a strong predictor for development of inhibitors or anaphylactic reactions on FIX treatment. Carrier diagnosis in sporadic case of hemophilia A or B, which encompasses around 50-60% of all newly diagnosed cases, may be a problem. In about 70-80% the mother of a sporadic case also carries the mutation and is thus a carrier. In the remaining 20-30% of cases a mutation can not be found and these women may be true non-carriers or being gonadal mosaics, i.e. it is not possible to conclude if she is a non-carrier or carrier. Mosaicism may cause a problem when genotyping mothers of a sporadic case of hemophilia A. Studies indicate that, depending on the type of mutation, approximately 20% are gonadal mosaics [@Leuer-01-AJHG]. However, in hemophilia B this seems to be rare [@Green-99-AJHG].

Prenatal diagnosis (PND) can be achieved by chorionic villus sampling during the 11 to the 13th week of gestation and karyotype analysis can be performed in order to determine fetal sex and in male fetuses be used to diagnose the mutation within 2-3 working days. The reasons for PND may be to prevent the birth of an affected boy by termination of the pregnancy, to prepare the obstetrical procedures or, for the parents-to-be, to psychologically prepare having a child with hemophilia.

Later in pregnancy amniotic fluid can be used as source of fetal DNA. Fetal sex determination can also be made by Y-chromosome analysis in blood from the pregnant woman very early in pregnancy and thus avoiding invasive diagnostic procedures in pregnancies with female foetus. Pre-implantation genetic diagnosis (PGD) enabling the implantation of female or unaffected male embryos has become possible [@Rallapalli-13-JTH; @Lavery-09-BJH; @Laurie-10-JTH]. PGD is a demanding procedure which however may be indicated in selected cases. 
