# Hemophilia nurse functions

#### Revision by: Linda Myrin Westesson (Gothenburg) and Malin Axelsson (Malmö) {-}

### Recommendations {-}

The functions of the haemophilia nurse may vary some in the centers of the Nordic countries, however the foundation of the function is care, education, communication and support.

The comprehensive care of persons with haemophilia (PWH) and other inherited bleeding disorders is complex and it requires a multidisciplinary team. The haemophilia nurse plays a key role in the comprehensive care of the PWH. The nurse educates PWH, parents and caregivers in illness management and has an important roll in supporting the PWH and the family. The nurse is a link between the PWH and the family, the haemophilia center and society [@Srivastava-13-HAE]. The functions of the haemophilia nurse may vary some in the centers of the Nordic countries, however the foundation of the function is care, education, communication and support.

The haemophilia nurse educates PWH, parents and other family members about haemophilia. He/she provides information and education about the illness to preschool, school, nursing homes and to other health care providers. The nurse also has close contact with local health care professionals and the PWH primary care contact. The nurse makes home visits when needed, as well as acting as a consult towards nurse colleagues when PWH are hospitalized. Ideally the haemophilia nurse coordinates and facilitates the comprehensive team meetings and collaborates within the multidisciplinary team.

As the population with haemophilia is ageing and co-morbidities will add to the complexity of the illness, the haemophilia nurse needs to focus not only on haemophilia. It´s also important to have a more holistic approach towards PWH and their families, if not to improve at least to maintain a good health-related quality of life for PWH [@Srivastava-13-HAE; @Colvin-08-HAE].

The nurse plays an important role as a supporter for newly diagnosed children and parents. He/she helps the family to adjust to the new situation with the illness and emphasize the healthy aspects of the child [@Myrin-Westesson-18-QHR]. The nurse recognizes and articulates the needs of the child, parents and other family members to the haemophilia team. The nurse educates the parents in home treatment and other aspects of the illness and encourages the parents to increase their knowledge about the illness and to independently be able to perform home treatment. Another important function is to provide information about haemophilia to preschool and school. The nurse has knowledge about haemophilia and complications that may occur from treatment or the illness itself. The hemophilia nurse is a resource, which parents or others around the child can turn to when they need guidance regarding haemophilia in daily life [@Harrington-16-HAE].

The supporting function of the nurse is vital for families with children affected by inhibitors [@Dekoven-14-HAE; @Dekoven2-14-HAE]. The nurse has to be aware of problem associated with inhibitors and the extensive treatment that the child needs. He/she educates parents on how to manage and handle the advanced ITI treatment in a central venous access device [@Schrijvers-12-HAE].

The nurse has knowledge about challenges at different life stages such as: childhood, adolescence, young adults and elderly. The life stages affect and influence the treatment and management of the haemophilia in different aspects and the nurse adapt her/his way of work and interacting. Over all, personal centre care is crucial for the success of achieving good self-management and self-reliant PWH [@Harrington-16-HAE; @Schrijvers-12-HAE; @Petrini-07-HAE; @Lindvall-14-PBC].

The haemophilia nurse has knowledge of the inherited aspects of the illness and can perform basic genetic counseling. The nurse recognizes the female carriers and is aware of their bleeding risk [@Harrington-16-HAE].

The haemophilia nurse has many functions among which the most important are:

*	Educate about illness management and home treatment

*	Support PWH and their families

*	Plan and participate in regular follow-ups at the haemophilia treatment center (HTC)

*	Perform administration of factor concentrates and blood samples

*	Telephone counseling to PWH, parents, preschool and other health care professionals

*	Guide and educate other health care professionals in- and outclinic

*	Consultant role to colleague nurses when PWH is hospitalized

*	Inform preschool, school and nursing homes etc. about haemophilia

*	Keep and update haemophilia registries

*	Participate in research and clinical trails

*	Participate in nursing research and developing project about haemophilia and other inherited bleeding disorders
