# Organisation of hemophilia care

#### Revision by: Riitta Lassila (Helsinki) {-}

\hfill\break

Since the early days of the treatment of hemophilia and other bleeding disorders the aim of the management has been to transform the severe disease form to a moderate, and currently to a mild one. The expert care, including regular replacement therapy or prophylaxis to avoid unnecessary bleeding complications, is best tailored, overseen and followed-up by the comprehensive care centers (CCC). European Association of Hemophilia and Allied Disorders (EAHAD) is the umbrella under which the Nordic Hemophilia care is networked with the other European major centers. European Hemophilia CCC (EHCCC) organizes the lifetime services provided by different disciplines around the patient’s medical needs (<a href>www.eahad.org</a>). On call services at necessity secures the expert management during emergency; severe illnesses, major trauma and surgical interventions.  Provision of early diagnosis, pediatric and family care, through the adolescent years and transition clinics, genetic counseling, including attention to carrier and obstetric issues (see chapter ”Carriers of hemophilia”), leads to the optimal comprehensive management to all patients and families with this inherited diseases. The prospective patient registers nationally and the safety surveillance at the European level by EUHASS (European Haemophilia and Allied Disorders Safety Surveillance) are of major importance to gather important outcome and safety data on most of the known bleeding disorders.

In the future, medical challenges among the ageing hemophilia population will call upon new bleeding disorder-specific approaches in the multidisciplinary management of co-morbidities, such as cancer and cardiovascular disease [@Hermans-14-CROH]. In Europe the national responsibility is to organize the centralized care of rare diseases overall, and the case of hemophilia provides a benchmark, as this inherited disease has organization of care and treatment options. The local policies, support from the authorities, national bodies and patient organizations should be engaged to the above aims. The EUHANET project has a EU- and pharmaceutical industry -funded has harmonized hemophilia care across Europe (<a href>www.euhanet.org</a>).

The historical role from the first injection of a FVIII concentrate given in Sweden to the developed modern care has paved the way for the hemophilia treatment worldwide [@Nilsson-92-JIM]. The fundamentals rely on the close interaction between the laboratory and clinics. This interaction establishes the diagnosis, provides opportunities to tailor prophylaxis, treatment of bleeds and management of major surgery with proper dosing of coagulation factor and appropriate follow-up.  Also, the diagnosis of the significant complications of hemophilia, i.e. inhibitors and infections, are based on laboratory medicine. In fact, the laboratory services are to be arranged to cover emergency services by the EUHANET criteria (Table \@ref(tab:EUHANET)), which match with the current practices in our Nordic centers. Under the current economical constraints the center leaders and practical staff should establish the health economical guidance, to maintain and strengthen the discipline locally in front of the regulators.

The two EUHANET center categories include European Hemophilia Treament Centers (EHTC) and EHCCC. Since our Nordic populations are concentrated in the large cities, networking activities are needed to provide access to care. This Nordic Hemophilia council platform presents uniform recommendations for the diagnosis and management of coagulation disorders (<a href>www.nordichemophilia.org</a>). The Nordic cooperation has been ongoing since decades and was formalized in 1999 as the Council. The Council provides guideline documents, organizes annual meetings and forms working groups to address topical issues.

## Multidisciplinary activities

According to the recommendations of World Federation of Hemophilia, EAHAD and EUHANET, multidisciplinary activities should be readily available for patients with hemophilia [@Colvin-08-HAE; @Soucie-00-BLOOD]. These CCC activities have been shown not only to reduce mortality but decrease morbidity and days of absence from school and work [@Soucie-00-BLOOD]. The patients need consultation line to the Center in any practical daily life and acute problems. Algorithms for emergency care aim at securing immediate management to avoid complications and increased treatment costs due to delayed replacement therapy. Management of joint disease, rehabilitation, and planning for interventions as a multi-expert effort should be well coordinated. Also, carrier, obstetric and perinatology issues need predesigned approach, written plans  and consultation chains.

Scandinavian centers have actively conducted and participated to hemophilia studies, including issues of inhibitor development and novel therapies.

## Registries

Surveillance of treatment safety and health economics is of utmost importance in hemophilia. The traditional inhibitor frequency may alter, new concentrates with their short pre-registration follow-up enter the market and new viral entities may appear, demanding continued surveillance. The Nordic CCCs have reported to the prospective EUHASS, which monitors mortality and the main health hazards including incidence of inhibitors, infections and thrombotic and any unexpected complications associated with treatment of hemophilia and allied disorders.  The national register capturing should be developed uniformly to enable comparison of the treatment across centers and entering to clinical studies according to the daily routines to ease the patient recruitment [@Lassila-10-HAE].

## Outcome analysis, QoL and health economy

The outcome evaluation of the patient should occur based on an established protocol including a functional self-assessment and objective performance, and the status of the joints should be evaluated and data collected to a register for comparisons. The basic SF-36/EQ5 quality of life (QoL) assessment tool or other QoL methods should be implemented to the patient management as an objective tool to evaluate the impact of the replacement therapy.

The regular prophylaxis is 4-8-fold more expensive than on demand mode of treatment, but good QoL is within reach if the prophylaxis is well tailored.. The treaters should raise active awareness of the costs of the treatment and look for the most cost-efficient individual solutions. Active individualization of the therapy should be based on clinical and pharmacokinetic (PK) evaluation (WAPPSHemo recommended as the global population based-PK) as the standard of care. The health economy of the current therapy in the era of the novel non-replacement therapies is an important task, which by linking the register data on patient follow-up and outcome can unravel the cost efficiency.

\newpage

Table: (\#tab:EUHANET) EUHANET criteria [@EUHANET] for the center status of EHCCC and EHTC

| |
|-|
| * Delivery of hemophilia care |
| * Standard and general requirements |
| * General policy and objectives, policies and procedures |
| * Record and data collection |
| * Organization, personnel appraisal and continuing education |
| * Supply and management of therapeutic products, reagents and medical devices |
| * Quality planning, evaluation and improvement |
| * Participation in registries related to inherited and acquired bleeding disorders |
| * Participation in clinical research |
| * Awareness, information and education of patients and their families |
| * Diagnosis of hemophilia and other related bleeding disorders and all forms of acquired hemophilia |
| * Therapy of hemophilia and other related bleeding disorders and all forms of acquired hemophilia |
| * Treatment program, prophylaxis, home treatment plan |
| * Treatment of acute bleeds and prevention, emergencies, treatment outside normal working hours |
| * Elective surgery |
| * Treatment of patients with inhibitors, including immune tolerance |
| * Treatment of patients with chronic viral infections |
| * Treatment of patients with acquired hemophilia and acquired vWD |
| * Periodic clinical and multidisciplinary review |
| * Genetic services |
| * Outcome indicators |
| * Advisory service |
| * Network of clinical and specialized services in conjunction with the hemophilia team |
