# Physiotherapy

#### Revision by: Elisabeth Brodin (Göteborg) {-}
#### Reviewed by Marianne Berg and Ruth Elise Dybvik (Oslo), Karin Juel Hansen and Lise Karlmark (Copenhagen) {-}

### Recommendations {-}

**Summary of physiotherapy work at treatment centers in the Nordic countries:**

* Informs about the joints and muscles function to parents, teenagers and adults

* Assess physical activity, joint mobility and muscle strength

* Proposes appropriate recreational and sporting activities

* Tests out and practicing assistive devices

* Designs exercise programs after a bleeding disorder

* Patients exercise to increase mobility and muscle strength

* Patients exercise before and after orthopedic surgery

* Treatments for pain relief

* Is a resource for colleagues outside the treatment center

## Introduction

The role of the physiotherapist in the treatment of the hemophilia patients has changed over the years because of the improvement of the medical treatment [@Nilsson-92-JIM].

Physiotherapy for the hemophilia patient is divided in to three categories: Prevention, assessment and treatment/rehabilitation.

## Prevention

Patients will at an early age receive prophylaxis with coagulation factor concentrates and can be physically active to the same extent as non-hemophiliac children resulting in normal physical strength and mobility [@Engelbert-08-JP]. Low physical activity can result in impaired bone mineralization and reduced bone mineral density in children with hemophilia compared with healthy [@Tlacuilo-08-BJH]. Moderate intensity of aerobic walking exercise improves bone metabolism and hand grip strength in adult persons with moderate hemophilia A [@AlSharif-14-AHS]. Good function of muscles around the joints has been shown to prevent joint and muscle bleeds. It is therefore essential to train muscle strength, endurance, and coordination at an early age [@Gomis-09-HAE]. Not only patients with hemophilia, but everybody (both adults and children) should be physically active for 30–60 min every day. The physiotherapist has an important role in informing and supporting PWH and their families about physical activity and sports that are appropriate for PWH [@Heijnen-08-HAE].

PWH experience the same benefits of exercise as the general population, being physically healthier than if sedentary and enjoying a higher quality of life (QoL) through social inclusion and higher self-esteem [@Runkel-17-HAE; @Negrier-13-HAE]. PWH can also gain physically from increased muscle strength, joint health, balance and flexibility achieved through physiotherapy, physical activity, exercise and sport [@Negrier-13-HAE; @Runkel-16-HAE]. The physiotherapist can also educate parents how to examine the joint mobility of the youngest children for early detection of joint bleeding.

## Assessment

Assessment instruments that are disease specific for PWHs have been developed over the past 10 years [@Beeton-06-HAE]. 
The physiotherapist will assess the joint and muscle function during the annual control at the treatment center. This includes joint mobility, muscle strength, pain, joint and muscle contractures, axial changes in the joints, balance and gait functions.

In acute bleeding a physiotherapist can help with differential diagnosis between joint and muscle bleeding and synovitis together with the physician. Ultrasound can complete the assessment for a correct diagnose [@diMinno-17-JCM]. When US imaging performed and scoring by physiotherapists using Hemophilia Early Arthropathy Detection (HEAD-US) [@Martinoli-13-TH] there is a good overall repeatability of the protocol and this complements the physical examination when screening and monitoring joint health of people with hemophilia [@Stephensen-18-HAE].

The Hemophilia Joint Health Score (HJHS) has been developed for children from 4 to 16 years of age and it is validity and reliability tested. It is used for the evaluation of joints in children and young adults [@Hilliard-06-HAE; @Fischer-13-HAE]. For adults and elderly patients the HJHS needs to be complemented with assessment of possible age-related conditions for example problems with the hip and shoulder joints.

Other evaluation instruments that may be present are visual analog scale (VAS) to rate the pain experience in daily activities or at acute trauma/bleeding [@Callahan-87-AR]. Hemophilia Activities List (HAL) can be used to get the patient's own perception of their ability in terms of activity (a person carrying out a task or action) and participation (a person's involvement in a life situation) [@vanGenderen-06-HAE].

Based on our examination we can recommend relevant steps that can benefit PWH such as contact to occupational therapist, when the patients need assisted devices at home for the ADL (activities of daily living). A disease-specific ADL status is developed in India [@Poonnoose-05-HAE] but is not used in the Nordic Countries at the moment due to cultural differences between the countries that makes the manual not suitable for the Nordic conditions. The generic self-administered questionnaire, “Health Assessment Questionnaire Disability Index” (HAQ-DI) could be used as a self-reported functional status when FISH or HAL is not useful [@Corte-Rodriguez-17-TR].

## Intervention (treatment/rehabilitation)

The purpose of rehabilitation of hemophilia arthropathy and after an acute bleeding in the joint or muscle is to reduce pain, restore joint mobility and muscle strength. Repeated bleedings in a joint leads to cartilage damage and give a hemophilia-related joint disease (hemophilia arthropathy). Active exercise under the guidance of a physiotherapist in combination with intensive treatment with factor concentrate can break the vicious circle. The results are better the sooner physiotherapy begins [@Gurcay-08-RI].

In the acute phase the early management can summarize as PRICE meaning Protection and joint Rest, relive acute pain with Ice and prevent and treat swelling with Compression and Elevation [@Hanley-17-HAE]. The physiotherapist plans an exercise program to restore lost function. Several studies show that mobility and strength exercise leads to faster normalization of the function and also significantly reduces the risk of permanent disability [@Gomis-09-HAE; @Guodemar-18-Hamost].

Treatment may include different types of mobility exercises (active, active unloaded, passive), posture instructions, careful manual extractions for increased mobility and pain relief purposes, strength and endurance exercise, coordination training, etc. Exercise in warm basin can be useful as pain relief like TENS, heat and cool pack [@Heijnen-08-HAE; @Hanley-17-HAE; @Young-14-HAE]. Techniques used in routine clinical practice can be used if the person with hemophilia have appropriate treatment with clotting factor [@Hanley-17-HAE]. There is a lack of confidence in the evidence for exercise in persons with hemophilia due to small numbers of randomized controlled trials but no adverse effects are reported in the different exercise intervention studies published [@Strike-16-CDSR; @Stephensen-18-TAH]. Recommended frequency is 3 times per week to reach desired results [@Heijnen-08-HAE].

Patients undergoing orthopedic surgery, for example synovectomy or different types of joint replacement receive physiotherapy exercise both before and after surgery [@deKleijn-06-HAE]. Before surgery it is important to train muscle strength around the joints and maintain the mobility that exists. After surgery the patient trains their mobility and strength according to the actual programs/protocol at the orthopedic clinic for the current operation. If the hemophilia-related arthritis has caused malalignment, stiffness and pain, the physiotherapist may prescribe or recommend orthotics and orthopedic shoes together with the attending orthopedic surgeon depending on the rules in different countries [@Heijnen-05-STH]. The physiotherapist also tests out walking aids and recommend other appliance needed in daily life. 
